# Generated by Django 4.2.2 on 2024-01-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='trend_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
