# Generated by Django 4.2.2 on 2024-01-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_category_trend_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
