# Generated by Django 5.0.1 on 2025-03-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_notebook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notebook',
            new_name='Lookbook',
        ),
    ]
