# Generated by Django 5.0.1 on 2025-03-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_notebook_lookbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbook',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
