# Generated by Django 5.0.1 on 2025-03-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_lookbook_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_license', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_bin', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
