# Generated by Django 5.0.1 on 2025-03-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pettag_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettag',
            name='additional_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pettag',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pettag',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pettag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pettag',
            name='qr_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
