# Generated by Django 5.0.1 on 2025-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pettag_additional_note_alter_pettag_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettag',
            name='dob',
        ),
        migrations.AddField(
            model_name='pettag',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
