# Generated by Django 5.0.1 on 2025-03-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('SSLCommerz', 'SSLCommerz'), ('Cash On Delivery', 'Cash On Delivery')], max_length=20),
        ),
    ]
